version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9091:9091
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env