apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-project-postgres-config
  namespace: devops
data:
  POSTGRES_DB: e-shop
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-project-postgres-secret
  namespace: devops
type: Opaque
data:
  password: cm9vdA==
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devops-project-postgres-pvc
  namespace: devops
  labels:
    app: devops-project
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devops-project-postgres
  namespace: devops
spec:
  serviceName: devops-project-postgres-service
  selector:
    matchLabels:
      app: devops-project
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: devops-project-postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-project-postgres-secret
                  key: password
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            - name: devops-project-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: devops-project-postgres-data
          persistentVolumeClaim:
            claimName: devops-project-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: devops-project-postgres-service
  namespace: devops
spec:
  selector:
    app: devops-project
  ports:
    - protocol: TCP
      port: 5432
