apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-project-postgres-config
  namespace: devops
data:
  POSTGRES_DB: e-shop
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-project-postgres-secret
  namespace: devops
type: Opaque
data:
  password: cm9vdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment
  namespace: devops
spec:
  replicas: 5
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: projectkiii
          image: vitruvianarendt/projectkiii:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: devops-project-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-project-secret
                  key: password
