name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag vitruvianarendt/projectkiii:latest

    - name: Push Docker Image
      run: docker push vitruvianarendt/projectkiii:latest
